apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trusted-profile-analyzer
  namespace: gitops-resources
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: gitops-resources 
  source:
    repoURL: https://charts.openshift.io/
    targetRevision: 1.1.1
    chart: redhat-trusted-profile-analyzer
    helm:
      parameters:
        - name: appDomain
          value: PLACEHOLDER_APP_DOMAIN
        - name: oidc.issuerUrl
          value: PLACEHOLDER_OIDC_ISSUER
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tssc-tpa
  syncPolicy:
    automated: { prune: true, selfHeal: true }

