---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhtas-operator-group
  namespace: trusted-artifact-signer
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  upgradeStrategy: Default
