apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpa-pgsql-data
  namespace: tssc-tpa
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tpa-pgsql
  namespace: tssc-tpa
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ClusterIP
  ports:
    - name: data
      port: 5432
      targetPort: 5432
  selector:
    app: tpa-pgsql-bee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpa-pgsql-bee
  namespace: tssc-tpa
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      app: tpa-pgsql-bee
  replicas: 1
  template:
    metadata:
      labels:
        app: tpa-pgsql-bee
        phase: reference
    spec:
      volumes:
        - name: pgsql-storage
          persistentVolumeClaim:
            claimName: tpa-pgsql-data
      securityContext:
        runAsNonRoot: true
      containers:
        - name: tpa-pgsql-bee
          image: 'registry.redhat.io/rhel9/postgresql-16:1-1754433677'
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: tpa-pgsql-user
                  key: user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tpa-pgsql-user
                  key: password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: tpa-pgsql-user
                  key: dbname
          volumeMounts:
            - name: pgsql-storage
              mountPath: "/var/lib/pgsql/data"
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 20
